'use client'

import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip, Area, AreaChart, XAxis, YAxis } from 'recharts'

type RevenuePoint = { month: string; revenue: number }
type StatusPoint = { name: string; value: number; color: string }

export default function AnalyticsCharts({ revenue, statuses, currency }: { revenue: RevenuePoint[]; statuses: StatusPoint[]; currency: string }) {
  return <div className="mt-10 grid gap-6 xl:grid-cols-[minmax(0,1.6fr)_minmax(280px,0.8fr)]"><section className="min-w-0 border border-[#dfe5dd] bg-[#fbfcf8] p-5 sm:p-7"><div className="flex items-end justify-between"><div><p className="sans text-[10px] uppercase tracking-[0.18em] text-[#6f7c76]">Collected revenue</p><h2 className="mt-2 text-3xl tracking-[-0.04em]">Last 6 months</h2></div><span className="sans text-xs text-[#6f7c76]">{currency}</span></div><div className="mt-8 h-[280px] w-full"><ResponsiveContainer width="100%" height="100%"><AreaChart data={revenue} margin={{ top: 8, right: 8, left: -20, bottom: 0 }}><defs><linearGradient id="revenueFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#718b12" stopOpacity={0.3} /><stop offset="100%" stopColor="#718b12" stopOpacity={0.02} /></linearGradient></defs><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: '#6f7c76', fontSize: 11 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: '#6f7c76', fontSize: 11 }} tickFormatter={(value) => `${currency} ${value >= 1000 ? `${Math.round(value / 1000)}k` : value}`} /><Tooltip formatter={(value) => [`${currency} ${Number(value).toLocaleString()}`, 'Revenue']} contentStyle={{ border: '1px solid #dfe5dd', background: '#fbfcf8', fontFamily: 'Arial', fontSize: 12 }} /><Area type="monotone" dataKey="revenue" stroke="#718b12" strokeWidth={3} fill="url(#revenueFill)" /></AreaChart></ResponsiveContainer></div></section><section className="border border-[#dfe5dd] bg-[#fbfcf8] p-5 sm:p-7"><p className="sans text-[10px] uppercase tracking-[0.18em] text-[#6f7c76]">Portfolio mix</p><h2 className="mt-2 text-3xl tracking-[-0.04em]">Invoice status</h2><div className="relative mt-5 h-[220px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={statuses} dataKey="value" nameKey="name" innerRadius={62} outerRadius={88} paddingAngle={3} stroke="none">{statuses.map((entry) => <Cell key={entry.name} fill={entry.color} />)}</Pie><Tooltip contentStyle={{ border: '1px solid #dfe5dd', background: '#fbfcf8', fontFamily: 'Arial', fontSize: 12 }} /></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 flex items-center justify-center"><div className="text-center"><p className="sans text-2xl font-bold">{statuses.reduce((sum, item) => sum + item.value, 0)}</p><p className="sans text-[10px] uppercase tracking-[0.15em] text-[#6f7c76]">Invoices</p></div></div></div><div className="sans mt-2 space-y-3">{statuses.map((status) => <div key={status.name} className="flex items-center justify-between text-sm"><span className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: status.color }} />{status.name}</span><strong>{status.value}</strong></div>)}</div></section></div>
}
